server:
    port: 8081
spring:
    mvc:
        converters:
            preferred-json-mapper: gson
    application:
        name: AUTHENTICATIONAPI
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
    datasource:
        url: "jdbc:mysql://localhost:3306/users"
        username: "root"
        password: "root"
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8083/eureka
