server:
    port: 8081
spring:
    mvc:
        converters:
            preferred-json-mapper: gson
    application:
        name: AUTHENTICATIONAPI
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
    datasource:
        url: "jdbc:mysql://kbp7pqomca4c.eu-central-2.psdb.cloud/kwetter?sslMode=VERIFY_IDENTITY"
        username: "i0ztusobkany"
        password: "pscale_pw_4ityE8og2X-lj58FwFJfuGCd7UEC1MMP7E32Lhec80Q"
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8083/eureka
