## Prod profile, only loads this file when on production
spring:
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
    datasource:
        url: "jdbc:mysql://localhost:3306/users"
        username: "root"
        password: "root"
    config:
            activate:
                on-profile: prod
